### ISSUE TITLE
16 color blue

### ISSUE THREAD

**Issue by george-b** [martanne/dvtm#12]
I use the [base16 tomorrow](https://chriskempson.github.io/base16/#tomorrow) theme and the blue used by dvtm was a little off so I changed it from 68 to 4.

I've ended up defining a basic set of colors that I use in other customizations what do you think about adding something like the following to the default `config.def.h`?

``` patch
--- config.def.h        2015-11-06 10:32:53.000023000 -0600
+++ config.def.h.modified       2015-11-06 10:30:39.000353000 -0600
@@ -13,12 +13,26 @@

 enum {
        DEFAULT,
+       BLACK,
+       RED,
+       GREEN,
+       YELLOW,
        BLUE,
+       MAGENTA,
+       CYAN,
+       WHITE,
 };

 static Color colors[] = {
-       [DEFAULT] = { .fg = -1,         .bg = -1, .fg256 = -1, .bg256 = -1, },
-       [BLUE]    = { .fg = COLOR_BLUE, .bg = -1, .fg256 = 68, .bg256 = -1, },
+       [DEFAULT] = { .fg = -1,            .bg = -1, .fg256 = -1, .bg256 = -1, },
+       [BLACK]   = { .fg = COLOR_BLACK,   .bg = -1, .fg256 = 0,  .bg256 = -1, },
+       [RED]     = { .fg = COLOR_RED,     .bg = -1, .fg256 = 1,  .bg256 = -1, },
+       [GREEN]   = { .fg = COLOR_GREEN,   .bg = -1, .fg256 = 2,  .bg256 = -1, },
+       [YELLOW]  = { .fg = COLOR_YELLOW,  .bg = -1, .fg256 = 3,  .bg256 = -1, },
+       [BLUE]    = { .fg = COLOR_BLUE,    .bg = -1, .fg256 = 4,  .bg256 = -1, },
+       [MAGENTA] = { .fg = COLOR_MAGENTA, .bg = -1, .fg256 = 5,  .bg256 = -1, },
+       [CYAN]    = { .fg = COLOR_CYAN,    .bg = -1, .fg256 = 6,  .bg256 = -1, },
+       [WHITE]   = { .fg = COLOR_WHITE,   .bg = -1, .fg256 = 7,  .bg256 = -1, },
 };

 #define COLOR(c)        COLOR_PAIR(colors[c].pair)
```

**Comment by martanne** [comment]
In my opinion it doesn't make much sense to include these user specific color codes in the default configuration which doesn't use them. Also you define the "normal" (`.fg`) and 256 color mode (`.fg256`) colors to the same value. The idea behind these was that you can specify different colors depending on how many colors your terminal supports. I understand you get the desired result because you changed your default terminal settings, but you can't assume that for the default configuration.
