### ISSUE TITLE
Attaching in both TTY and X11: display and input glitches

### ISSUE THREAD

**Issue by sshbio** [martanne/dvtm#23]
It usually happen while creating dvtm on TTY and using it in X11, but I also got it in TTY once it have been attached to X11 first.  I don't get any issue while using it only in TTY or X11 without attaching in the each other.

While attaching in both TTY and X11 with abduco, display is not properly updated, as for vim, or less `^D` for half page down.  This cause the buffer to be updated at the upper part, and seldomly for the lower part.

This also makes the sequence `^[[?6c` appears:

- Randomly while typing;
- Systematically at the moment I attach dvtm on X11 after creating dvtm in TTY
- Systematically while pressing down some key on TTY, where the repetition frequency is higher (less time between two repetition);
- Periodically, like every second, without touching the keyboard.  I only got it once.

I tried to change the `-d delay` option delay either very high (`10000`) or very low (`0`), without significant result.

The way I checked was in vim, where the entered keys are displayed.
After waiting a few, the `^[[?6c` disappear from vim modeline, and the typed keys got executed (like `^[[?6cdddddddddd` is displayed in vim echo area, then after **1 second**, only `^[[?6c` is displayed and 10 lines are deleted).

Thank you for developping this multiplexer.  I really like it.  I can try to help, so don't hesitate asking me more details or twinkering the source.

**Comment by sshbio** [comment]
I noticed the same issue while using dtach instead of abduco.

I don't get the same issue while creating the session in X11 and attaching it in TTY.  It only insert the `^[[?6c` sequence while attaching.

**Comment by sshbio** [comment]
Nice! Setting the `NCURSES_NO_UTF8_ACS=1` variable fix both borders displayed as qqqqqqqqq in TTY and the `^[[?6c` being insteted.

This means DVTM only has some refresh issue, and a few more feature to gain to be perfect, but is now fully functionnal, and totally rocks!

That is really awesome and I am very happy right now. :)

**Comment by sshbio** [comment]
As a workaround, I use <kbd>MOD</kbd> <kbd>r</kbd> to redraw the screen.

**Comment by martanne** [comment]
The way `abduco` works is that it purely redirects I/O, it does not attempt to analyze the underlying data stream for escape sequences etc. Hence when you reattach with a different type of terminal you essentially change the world `dvtm` is living in, without telling it. This will cause all sorts of issues (if the terminals are sufficiently incompatible as is the case for tty and X11).

To "solve" this, dvtm would have to be notified that a session is reattached and what the new terminal is (i.e. `$TERM`). Given that information dvtm could then try to reinitialize curses with the new terminal type.

Even with these changes, it would never be possible to be simultaneously attached with a client from tty and one from X11. This is just a consequence of the chosen design. If you need this kind of functionality you might be better of with tmux. Because it conflates session- and window management it is able to maintain an abstract terminal state which can then be output to each individual client.

abduco+dvtm is really optimized for environments where you reattach with the same type of terminal. The typical use case is to ssh into some server, start an abduco session, disconnect, then later reconnect again with the same kind of terminal.

**Comment by sshbio** [comment]
I remember that tmux avoided the issue.  I understand abduco + dvtm design, and now that I understand I prefer it like so.  Thank you for the explanation.

**Comment by sshbio** [comment]
This was easier than what I thought: `TERM=screen abduco -A dvtm dvtm-status` fixes the issue.
Setting the TERM to screen before to start `abduco`.
