### ISSUE TITLE
^[ as a modifier

### ISSUE THREAD

**Issue by josuah** [martanne/dvtm#39]
Using `^[` as a modifier, to use either Escape then key, or directly Alt + key.

It already works, I can switch window with `Alt + j` but I then need to press any key, which will be sent to the client.

Would it be easy to fix?  If not, Ctrl + Space is pretty great already.

I am having a lot of fun with `dvtm` and `abduco`.  Thank you!

**Comment by martanne** [comment]
I would recommend against using Escape or Alt as modifier because then you also have to worry about timing related issues. If you do it anyway dvtm's input code currently expects <kbd>Escape</kbd><kbd>j</kbd> as two different keys. If there is not enough time between them it will get interpreted as <kbd>Alt+j</kbd> which has the same underlying representation but is a single key. Thus dvtm waits for another key which is then sent to the client.

**Comment by josuah** [comment]
It is all right.  It is not worth a large addition of complexity, or unexpected behavior at other places (Mod + PageUp woul probably break).

**Comment by craigbarnes** [comment]
> I would recommend against using Escape or Alt as modifier because then you also have to worry about timing related issues.

When running dvtm inside xterm, pressing <kbd>Alt<kbd>+<kbd>x<kbd> seems to send the string "\xc3\xb8" which is a valid UTF-8 encoding for the Norwegian `ø` character. Isn't clashing with valid UTF-8 sequences a bigger problem than working around <kbd>Escape<kbd> vs. <kbd>Meta<kbd> timing issues...?

**Comment by craigbarnes** [comment]
I guess the solution is just to turn on `metaSendsEscape` in the xterm options instead of tring to send the escape sequence through dvtm.
