### ISSUE TITLE
Failed to install on OSX Sierra using homebrew

### ISSUE THREAD

**Issue by erf** [martanne/dvtm#43]
I got the following error whilst tryting to install `dvtm` via `homebrew`:
"dvtm: This formula either does not compile or function as expected on macOS
versions newer than Yosemite due to an upstream incompatibility."

Version info:
macOS Sierra 10.12.1 (16B2555)
homebrew 1.1.1

**Comment by erf** [comment]
I tried to build it from source and i got the following error:
```
CC dvtm.c
dvtm.c:956:12: error: use of undeclared identifier 'SIGWINCH'
        sigaction(SIGWINCH, &sa, NULL);
                  ^
dvtm.c:1779:23: error: use of undeclared identifier 'SIGWINCH'
        sigaddset(&blockset, SIGWINCH);
                             ^
2 errors generated.
make: *** [dvtm.o] Error 1
```

It seem this is the same problem as in: https://github.com/martanne/vis/issues/302

**Comment by martanne** [comment]
See #30. You are currently expected to set the needed feature test macros for your system in `config.mk`. A slightly more (end) user friendly approach would probably be to introduce a handwritten `configure` script which auto detects these things.

Also the formula is probably disabled because apparently dvtm currently won't work on modern macOS systems due to #19.

**Comment by erf** [comment]
Thanks. Adding `CFLAGS += -D_DARWIN_C_SOURCE` worked. A `configure` script would be helpful.

It did not hang on close, but i disapled [SIPS](https://en.wikipedia.org/wiki/System_Integrity_Protection) previously. 

I noticed my `.bash_profile` is not loaded when i create a new window.
