### ISSUE TITLE
dvtm uses wrong background color when the terminal title is set

### ISSUE THREAD

**Issue by ajgrf** [martanne/dvtm#44]
I'm getting the wrong background color under the following conditions. First I set the background color of all dvtm's ui elements to cyan (it looks fine with my color scheme). This seems to work - dvtm elements are cyan and windows have a normal background - until a window sets the terminal title. After that, the window uses cyan as a background color even in the shell!

I've reproduced this under gnome-terminal and st, and my shell prompt doesn't use any colors.

**Comment by martanne** [comment]
Thanks for the report. The problem was actually the other way around. Assuming you modified the `DEFAULT` color, the whole window should use cyan from the start. The reason being that it is referenced from the [colorrules array](https://github.com/martanne/dvtm/blob/master/config.def.h#L143).

You should change it or define and use your own color. If you do so, it should work. Feel free to re-open the issue if this is not the case.

**Comment by ajgrf** [comment]
That was the problem, thank you!
