### ISSUE TITLE
Shift-PageUp

### ISSUE THREAD

**Issue by antoyo** [martanne/dvtm#56]
The [doc](https://github.com/martanne/dvtm/blob/b45828dcc86dba889386d4052410d95e7e78eebe/dvtm.1#L142) says that `Shift-PageUp` should scroll back but it does not work.
The shortcut `Mod-PageUp` works thought.
Could you please add the missing shortcut.
Thanks.

**Comment by martanne** [comment]
The "shortcut" is already there. For example it works with [st](http://st.suckless.org/) which doesn't provide an internal scroll back buffer and as a result doesn't intercept `Shift-PageUp` keys.

The problem is likely that the environment from which you run dvtm (e.g. a X terminal emulator) consumes the `Shift-PageUp` keys.

Maybe `MOD+e` (copy mode using your editor) or `MOD+E` (scroll back history using your pager) is a usable alternative.

**Comment by antoyo** [comment]
That was indeed an issue with the terminal, `alacritty`.
I added these lines to the config file:
```
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
```
and now it works.
